name: sh-qip-cx

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-php # Щоб не підставлявся index_suffix 'app-1'
    image: php:8.3-fpm-alpine # 33 MB
    #image: bitnami/php-fpm:8.3 # 106 MB
    #image: bitnami/laravel:11  # 255 MB
    #build:
    #  context: ./docker
    #  dockerfile: Dockerfile
    volumes:
      - ./:/app/:cached
    working_dir: /app
    environment:
      TZ: '${APP_TIMEZONE:-Europe/Kiev}'
    networks:
      - app-network

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    #image: nginx:latest # 70 MB
    #image: nginx:mainline-alpine # 20 MB
    #image: nginx:mainline-alpine-slim # 7 MB
    #image: nginx:stable-alpine # 20 MB
    image: nginx:stable-alpine-slim # 7 MB
    volumes:
      - ./:/app/:cached
      #- ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/sh.qip.cx.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /app
    ports:
      - "${APP_PORT:-8024}:80"
    environment:
      TZ: '${APP_TIMEZONE:-Europe/Kiev}'
      #- NGINX_HOST=foobar.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
